slack:
  report_channel: SLACK_REPORT_CHANNEL
  report_channel_id: SLACK_REPORT_CHANNEL_ID

jira:
  project: JIRA_PROJECT
  issue_type_id: JIRA_ISSUE_TYPE_ID
  issue_type_name: JIRA_ISSUE_TYPE_NAME

secrets:
  cftptl-intsvc:
    jira-username: JIRA_USERNAME
    jira-api-token: JIRA_API_TOKEN
    rd-slack-bot-token: SLACK_BOT_TOKEN
    rd-slack-app-token: SLACK_APP_TOKEN